import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { barlow } from "./fonts/barlow";

import { ToastContainer } from 'react-toastify';

import 'react-toastify/dist/ReactToastify.css';
import AuthProvider from "@/providers/AuthProvider";
import QueryProvider from "@/providers/QueryProvider";
import CartProvider from "@/providers/CartProvider";
import ProductsProvider from "@/providers/ProductsProvider";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${barlow.className} antialiased`}
      >
        <AuthProvider>
          <QueryProvider>
            <CartProvider>
              <ProductsProvider>
                <div>
                  {children}
                </div>
              </ProductsProvider>
            </CartProvider>
          </QueryProvider>
        </AuthProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
